title: William P. de Paula 
logo: "/images/Foto-Perfil.png?raw=true" 
description: > 
  Morador da cidade de Coxim/MS, 36 anos, atualmente trabalha como desenvolvedor  Web FullStack 
  principalmente utilizando as tecnologias Java + Spring Boot e Vue.js.  Também tem experiencia na 
  linguagem Python, tendo desenvolvido alguns projetos particulares utilizando Django.
  Atualmente está cursando o 5º semestre de Sistemas da Informação - UFMS/Coxim e desde fev/2019 é 
  estagiário fullstack na empresa AZ Tecnologia em Gestão <a href="https://www.azi.com.br/">AZ Tecnologia em Gestão</a>
 
  <a href="https://www.linkedin.com/in/william-de-paula/">Perfil no LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-159575482-1
